- .github/workflows/publish.yml
Rework GitHub Pages publish using https://github.com/peaceiris/actions-gh-pages action
> ci(publish): rework gh pages deploy

- .github/workflows/publish.yml
> ci(publish): fix build working directory

- docusaurus.config.js
Seen with @JulienMassonnat. The "dark" theme is now the default theme.
> style: switch to dark theme by default

- README.md
Add the following badges:
- Conventional commits
- Licence
- Prettier
- Build
- Lint
- Publish
> Docs: add README badges

- README.md
- docusaurus.config.js
- package.json
- src/scss/custom.scss
- yarn.lock
Add some research capability using [easyops-cn/docusaurus-search-local](https://github.com/easyops-cn/docusaurus-search-local) plugin.
Search only works with statically built documentation (after a `yarn build`) and can be tested by using `yarn run serve` (after build). It won't work in development (running a `yarn start`).
> Feat: search

- docusaurus.config.js
- package.json
- yarn.lock
Add [mdx-mermaid](https://github.com/sjwall/mdx-mermaid) plugin.
> Feat: mermaid plugin

- docusaurus.config.js
This PR is pretty straightforward
> fix: update twitter broken link

- docs/whitepaper/introduction.md
A very few small improvements to my point of view ^^
> fix(introduction): improve some phrasing

- .gitignore
- docs/whitepaper/ds-business-models.md
The purpose of this PR is to add the description of the DS business models proposed by OKP4.
> feat: add dataspace business model

- docs/whitepaper/roles.md
This PR in the role section to factorize a sentence and to see if I got the meaning correctly.
> fix(roles): factorize and rephrase a sentence

- docs/nft-tutorial/en.md
- docs/nft-tutorial/fr.md
> style(nft-tutorial): make linter happy

- .github/workflows/lint.yml
This PR updates the docs project with a ci step recently fixed in project [eslint-config-okp4](https://github.com/okp4/eslint-config-okp4)
> ci: report new dependencies on pull requests

- docs/whitepaper/tokenomics.md
- docusaurus.config.js
- package.json
- yarn.lock
I think there is a little mistake in the staking reward calculation.
> Fix: staking reward calculation

- docs/whitepaper/dataverse.mdx
This PR corrects a small typo error
> fix: fix typos

- .github/workflows/auto-fix-md.yml
- .github/workflows/auto-merge.yml
- .github/workflows/build.yml
- .github/workflows/follow-contributor.yml
- .github/workflows/lint.yml
- .github/workflows/publish.yml
Update of ubuntu version in workflows
> ci: update ubuntu version

- docs/faq/faq.md
- docs/nft-tutorial/en.md
> Fix: typos

- docs/whitepaper/roles.md
- docs/whitepaper/token-model.md
I have center and resize the new illustrations on the whitepaper
> fix: center and resize illustrations

- docs/tech-documentation/ontology/general-principles.md
Highlight the ontological concepts in bold
> feat: put in bold ontology concepts

- docs/tech-documentation/ontology/general-principles.md
> fix: fix mermaid code block

- docusaurus.config.js
- src/scss/custom.scss
- src/scss/main.scss
Change color on dark-theme and light to orange, and delete ("work in progress") on navbar.
Delete picture meteorite of background.
Move the closing sidebar at the top left and move search bar on the left logo github and discord.
Add a button translation.
> Make link orange

- docs/tutorials/nonos-tuto-1.md
- docs/tutorials/nonos-tuto-2.md
- docs/tutorials/overview.md
- docs/tutorials/prolog-1.mdx
* Specify the ichiban predicates list, the difference with SWIPL
* Overview update with the missing link to the CLI tutorial
> Fixes on overview & prolog tutorials

- .github/workflows/build.yml
> ci(workflow): update max old space size to 8192

- docs/whitepaper/use cases.md
> feat: docs use cases

- src/scss/main.scss
This PR fixes the issue mentioned in #262
> fix: fix markdown code display on h3

- docs/tutorials/cli-1.mdx
- docs/tutorials/ontology-1.md
- docs/tutorials/prolog-1.mdx
All fixs from @JulienMassonnat / @MathieuConte / @MdechampG for the tutorials
> Typo fixs + more clarification for the first tutorials

- package.json
> build(project): specify explicit files for markdownlint

- docs/index.mdx
This PR add the Tutorials and Technical documentation cards to the home page.
<details>
<summary> Screenshots </summary>
</details>
> feat(whitepaper): add tutorials & Tech doc cards

- src/scss/custom.scss
- src/scss/main.scss
This PR update the hover colour of the header nav items.
<details>
<summary> Screenshots </summary>
</details>
> refactor(style): update header nav items hover color

- docs/whitepaper/solution.md
Following #302, makes some improvements to text rendering (text aeration, use of enumerated lists, etc.).
> Improve text style

- contracts_versioned_docs/version-v3.0.0/README.md
Solve broken links introduced by https://github.com/okp4/docs/pull/326
> fix: solve broken link to base v3.0.0 contracts doc
