axone-protocol/docs

.github/workflows/publish.yml

Force github pages publication with @bot-anik through `https`.

ci(publish): don't use ssh for gh publication

---

docusaurus.config.js

Update the `baseUrl` accordingly to the GitHub pages path.

fix: use /docs/ as base url

---

.github/workflows/lint.yml

ci(workflow): exclude dependabot PRs from commit lint

---

docusaurus.config.js

Because there is a redirection on `/docs` in `index.js`, we don't need to specify `/docs/` as baseURL in `docusaurus.config.js`, but only `/` instead.

Fix: blank page on /docs/

---

docusaurus.config.js
src/pages/index.js

With the help of @amimart & @ccamel, our DNS has been configured to redirect the domain `docs.okp4.network` to `okp4.github.io`.
Consequently, the following changes should be considered:
- update Docusaurus baseURL from `/docs` to `/`
- update redirection in `index.js` from `/docs/docs/whitepaper/abstract` to `/docs/whitepaper/abstract`

Chore: Update baseURL after DNS update

---

.github/workflows/publish.yml

We set up the CNAME redirect to the repository's github pages through `docs.okp4.network`, we need to specify it when publishing.

ci(pages): specify custom url targeted CNAME

---

.github/workflows/auto-fix-md.yml

Add a Github Action triggering everyday at midnight or manually to automatically fix markdown files.
Changes are commit using [Bot Anik](https://github.com/bot-anik).

CI: Auto fix markdown

---

package.json
yarn.lock

Add the [igorshubovych/markdownlint-cli](https://github.com/igorshubovych/markdownlint-cli) linter available from `yarn` under `lint` command.
This completes/fixes the PR #26. This allows developers to check markdown compliance under their local environment:
```
yarn lint
yarn lint:fix
```

build(dev-deps): add markdownlint-cli dev dependency

---

docs/whitepaper/token-model.md
docs/whitepaper/tokenomics.md

Correct some misspelling of _stake_, _staking_ and _stacking_ being different notions.
I replaced it everywhere it seems relevant to me, however, I may had a heavy-hand so I'll let you judge ⚖️.

fix: reword 'stack' to 'stake'

---

docusaurus.config.js
static/js/matomo.js

Add web analytics to the [Docusaurus website](https://docs.okp4.network/) web site using [matomo](https://matomo.org/).

chore: add matomo usage tracking

---

.github/workflows/bump-okp4d-version.yml

This PR brings a first step of automation of the `okp4d` version update (referenced in the `docs/nodes/data.json` file) to keep documentation in sync, and implemented as a parameterized workflow invocable by another workflow (typically [okp4/okp4d](github.com/okp4/okp4d)) (or possibly manually if necessary).
To come, the invocation of this workflow after release on the [okp4/okp4d](github.com/okp4/okp4d) project.

ci(workflow): add workflow to bump okp4d version

---

docs/index.md

Since the last [commit](https://github.com/okp4/docs/commit/91ab60e7243e43f625bf2d2775aba93138f67714) on main branch, the build failed, caused by a too many close html balise. 
@MdechampG Could you please check if this fix does not change the expected appearance on home page cards ☺️. 
This PR is needed for #136...

Fix build failure on index cards

---

static/js/redirect.js

Redirect not work if the `/docs` doesn't end by `/`.
@MdechampG FYI

🐛 Fix redirect for `/docs` path

---

.github/workflows/auto-fix-md.yml
.github/workflows/auto-merge.yml
.github/workflows/build.yml
.github/workflows/follow-contributor.yml
.github/workflows/lint.yml
.github/workflows/publish.yml

Bumps github runners to [ubuntu-22.04](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources).

⬆️ Update github action runners to ubuntu-22.04

---

.github/dependabot.yml

`dependabot` cannot add `maintainers` as reviewers, so this PR:
- adds named reviewers and assignees
- enhances the whole workflow

ci(dependabot): update reviewers and assignees

---

.github/workflows/update-versioned-docs.yml

Since https://github.com/okp4/docs/pull/139 PR, the workflow triggered to update docs on modules and contracts documentations is no longer working. The `docs` path has been removed and script was not updated accordingly.

🐛 Fix: remove docs folder from update docs workflow

---

.github/workflows/lint.yml

Restrain possible images format to WEBP, SVG, ICO.
Base verification on the actual format and not on the extension.

ci(lint): validate images

---

.github/workflows/update-versioned-docs.yml

Add new optional parameter to allow publish documentation in draft mode directly on main branch. Draft documentation is located in the `./<section>` folder, all files in this folder is indicated on docusaurus as the next release documentation.
A new PR (in progress) on okp4d project will notify each time a documentation has been updated on main branch and will be published in draft on this repository. 
This PR can be merged even if no PR has been created in okp4d repository or contract repository. It could be manually triggered on the [action section of GitHub.](https://github.com/okp4/docs/actions/workflows/update-versioned-docs.yml)

✏️ Draft module documentation

---

.github/workflows/update-versioned-docs.yml

Add a step to check if files changes in documentation before publish documentation PR or commit (in case of draft documentation)
🔗 Needed for [this PR](https://github.com/okp4/okp4d/pull/255) to avoid publish if no documentation has been changed.

📚 Docs: add changed files steps

---

.github/workflows/update-versioned-docs.yml
docs/nodes/kms.md

When trigger update docs from `okp4d` repository, two job is launched at the same time (`modules` documentation and `commands` documentation), when the first job push on repository, the second one failed since the ref has changed. To fix this I have added the concurrency option named `update-docs-${{ github.ref }}` that will make a queue and execute job once at a time.

🐛 Ci : remove concurrency on trigger update docs

---

.github/workflows/update-versioned-docs.yml

Another PR (again) to fix workflow docs update, this time it's for contracts repository that failed on the last (and first for this module) triggering. Ignore git rm if files doesn't exist.

🐛 Fix(ci): ignore unmatch file 

---

.github/workflows/update-versioned-docs.yml

This PR is again another PR to trying fix the release process of the module, contract and commands documentation. 
Publishing draft documentation is already working but there is an issue in GitHub action runner that traits boolean input as string and not as boolean : see https://github.com/actions/runner/issues/1483 that reference this issue.

🐛 Fix publish released docs

---

docusaurus.config.js

Add support for the prolog code on code block :

feat: add prolog codeblock support

---

docusaurus.config.js
package.json
yarn.lock

This is the triumphant return of PR #241 that was :sob: prematurely and unfairly closed by @bot-anik.
This PR adds support for [Kroki!](https://kroki.io/) in the docusaurus markdown. Kroki provides very nice support for several different textual diagrams like [plantUML](https://plantuml.com/fr/), [structurizr](https://github.com/structurizr/dsl) or [BPMN](https://bpmn.io/toolkit/bpmn-js/). This capability is very useful for creating technical diagrams, particularly for editing the technical part of the website.
- https://kroki.io/examples.html
- https://github.com/nice-move/remark-kroki

Add Kroki! support (2)

---

.github/workflows/publish.yml

Same than #251 - `publish` workflow was missing.

ci(workflow): update max old space size to 8192 for publish

---

.github/workflows/build.yml
.github/workflows/publish.yml
package.json

Self explanatory.
Move the `max_old_space_size` directive from the GitHub workflows to the `package.json` file in order to achieve the same outcome for a local environment.
(related to #252 and #251)

build(project): specify node max_old_space_size in package.json

---

docs/tutorials/explorer-sc.md

This PR replaces the links to resources with persistent links based on Git hashes (where relevant). This change aims to ensure the stability of tutorials and prevent broken or outdated references.

fix(tutorial): use persistent links where relevant

---

docs/tutorials/prolog-1.mdx

Revise the tutorial documentation to reflect changes in how the parameters of the Logic module are retrieved, following the chain's upgrade.

fix(tutorial): fix logic module params retrieval

---

.github/workflows/auto-fix-md.yml

ci(workflow): exclude generated documentation from linter

---

docusaurus.config.js
i18n/en/code.json
i18n/fr/code.json
src/scss/main.scss

This PR  update the toggle button for the navbar on mobile to be on the right side of the screen instead of the left side.
<details>
<summary> Screenshots </summary>

refactor: customize burger menu on right side

---

docs/whitepaper/architecture.mdx
docs/whitepaper/solution.md

Two minor typo fixs

---

docs/tutorials/cli-1.mdx

Tutorial about the CLI: add the command to move the `okp4d` binary to a folder declared in $PATH

Added instruction to fix "bash: okp4d not found" issue

---

docusaurus.config.js
sidebars.js

Move the api menu from the main navigation bar to the technical documentation sidebar.
We cannot reference by `docId` on the sidebar item since it's relative to the `docs` folder, while `contracts`, `modules` or `commands` are `docId` at the root path. So I put a [`link` menu type](https://docusaurus.io/docs/2.2.0/sidebar/items#sidebar-item-link). The only side effect of this is that if we change the path of one of the doc module, we need to change it on the sidebar too. But don't worry, when docusaurus build app, it will check all invalid links.

🪚 Refactor: move API menu

---

package.json
yarn.lock

Self explanatory. Bump `docusaurus/core` dependency to `v2.4.1`, this fixing version desynchronization between `core` and `plugin-content-pages` leading to errors in CI logs.
Note:
- didn't understand why Dependabot did not intervene to suggest a version upgrade.
- It's also odd that the logged error does not result in a build failure, and from what I can see, there is no option to enforce this.

build(deps): bump @docusaurus/core to 2.4.1

---

package.json
yarn.lock

This is a proposal to introduce quizzes in the academy section using the [react-quiz-component](https://www.npmjs.com/package/react-quiz-component) that makes it easy to present quizzes to users. This component offers many features like title and synopsis, input validation, multiple-answer options with single or multiple correct answers, support for text and photo answers, explanations for answers, instant feedback, retry options, etc.
This PR simply declares the dependency so that quizzes can be managed in the documentation.
Example:

build(deps): add react-quiz-component@0.7.1

---

docusaurus.config.js
sidebars.js

This PR addresses the issue of a broken link in the technical documentation of [contracts v4.0.0](https://github.com/okp4/contracts/releases/tag/v4.0.0). This issue prevents the deployment of any new updates to the docusaurus site.
The problem lies with the file `README.md` that has been removed in the PR https://github.com/okp4/contracts/pull/311,  part of this release. This file served as the default page for the technical documentation of contracts. To fix this, we simply designate `okp4-cognitarium` as the target (the same way we already do for ontology, modules, etc.)

build(project): fix broken link on contracts v4.0.0

---

docs/getting-started/quickstart-guides/describe-resource.mdx

Add a prompt marker to the beginning of commands to differentiate from their results in the describe resource page.
I decided to use `>` as marker but we can ship another.. I didn't check other pages for this need.

style: make cmd visible on describe resource doc
